AWSTemplateFormatVersion: '2010-09-09'
Description: 
Parameters:
  BucketName:
    Type: String
    Description: Name of S3 bucket

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead # TODO check
      PublicAccessBlockConfiguration: # TODO check
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false      
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
        - Sid: PublicReadForGetBucketObjects
          Effect: Allow
          Principal: '*'
          Action: s3:GetObject
          Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]

Outputs:
  WebsiteBucket:
    Value: !Ref WebsiteBucket
    Description: Name of S3 bucket
  WebsiteURL:
    Value: !GetAtt 
      - WebsiteBucket
      - WebsiteURL
    Description: HTTP URL for website hosted on S3    