AWSTemplateFormatVersion: "2010-09-09"

Description: |
  Template for creating a static website hosted on S3 and served through CloudFront via HTTPS with a custom domain name

Parameters:
  S3BucketName:
    Description: Name of S3 Bucket
    Type: String

  Route53DomainName:
    Description: Name of Route53 Domain
    Type: String

  AcmCertificateArn:
    Description: ARN of ACM Certificate
    Type: String

Resources:

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html
  S3Bucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html    
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal: '*'
            Resource: !Join ["", ['arn:aws:s3:::', !Ref S3Bucket, /*]]

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudfront-distribution.html
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        IPV6Enabled: true
        PriceClass: PriceClass_All
        Origins:
          - DomainName: !Select [1, !Split [//, !GetAtt S3Bucket.WebsiteURL]]
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        Aliases:
          - !Ref Route53DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only

  #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-route53-recordsetgroup.html
  Route53RecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:

      # Specify either HostedZoneName or HostedZoneId, but not both. If you have multiple hosted zones with the same domain name, you must specify the hosted zone using HostedZoneId.
      HostedZoneName: !Join ["", [!Ref Route53DomainName, .]]

      # If IPv6 is enabled for the distribution, create two resource record sets to route traffic to your distribution, one with a value of A and one with a value of AAAA.
      RecordSets:
        - Name: !Ref Route53DomainName
          Type: A
          AliasTarget:

            # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid            
            HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
            DNSName: !GetAtt CloudFrontDistribution.DomainName
        - Name: !Ref Route53DomainName
          Type: AAAA
          AliasTarget:

            # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid            
            HostedZoneId: Z2FDTNDATAQYW2 # CloudFront hosted zone ID
            DNSName: !GetAtt CloudFrontDistribution.DomainName

Outputs:
  S3WebsiteUrl:
    Description: HTTP URL for S3 website endpoint
    Value: !GetAtt S3Bucket.WebsiteURL

  CloudFrontWebsiteUrl:
    Description: HTTPS URL for Cloudfront distribution endpoint
    Value: !GetAtt CloudFrontDistribution.DomainName

  Route53WebsiteUrl:
    Description: HTTPS URL for Route53 domain name
    Value: !Join ["", ['https://', !Ref Route53DomainName]]
